parameters:
- name: publishWeb
  type: boolean
  default: false
- name: configuration
  type: string
  default: $(BuildConfiguration)
- name: outputPath
  type: string
  default: $(build.artifactStagingDirectory)/publish

steps:
- task: DotNetCoreCLI@2
  displayName: Publish projects
  inputs:
    command: 'publish'
    configuration: ${{ parameters.configuration }}
    publishWebProjects: ${{ parameters.publishWeb }}
    arguments: 'src/**/*.csproj --no-restore --no-build --no-self-contained --nologo -o ${{ parameters.outputPath }}'
